import ColumnType from '~/models/database/ColumnType';
import { DatabaseType } from './DatabaseType';

const databaseColumns: ReadonlyMap<DatabaseType, readonly ColumnType[]> = new Map<DatabaseType, readonly ColumnType[]>([
    ["postgres", [
        new ColumnType({ id: 1, name: 'bit', description: '固定長ビット列', baseQuery: 'BIT', withPrecision: false, withScale: false }),
        new ColumnType({ id: 2, name: 'bit (n)', description: '固定長ビット列', baseQuery: 'BIT[[PARAM]]', withPrecision: true, withScale: false }),
        new ColumnType({ id: 4, name: 'bit varying', description: '可変長ビット列', baseQuery: 'BIT VARYING', withPrecision: false, withScale: false }),
        new ColumnType({ id: 5, name: 'bit varying (n)', description: '可変長ビット列', baseQuery: 'BIT VARYING[[PARAM]]', withPrecision: true, withScale: false }),
        new ColumnType({ id: 6, name: 'boolean', description: '論理値 (真/偽)', baseQuery: 'BOOLEAN', withPrecision: false, withScale: false }),
        new ColumnType({ id: 367, name: 'bytea', description: 'バイナリデータ (「バイトの配列 (byte array)」)', baseQuery: 'BYTEA', withPrecision: false, withScale: false }),
        new ColumnType({ id: 11, name: 'smallint', description: '2バイト符号付き整数', baseQuery: 'SMALLINT', withPrecision: false, withScale: false }),
        new ColumnType({ id: 51, name: 'smallserial', description: '自動増分2バイト整数', baseQuery: 'SMALLSERIAL', withPrecision: false, withScale: false, foreignId: 11 }),
        new ColumnType({ id: 15, name: 'integer', description: '4バイト符号付き整数', baseQuery: 'INTEGER', withPrecision: false, withScale: false }),
        new ColumnType({ id: 55, name: 'serial', description: '自動増分4バイト整数', baseQuery: 'SERIAL', withPrecision: false, withScale: false, foreignId: 15 }),
        new ColumnType({ id: 17, name: 'bigint', description: '8バイト符号付き整数', baseQuery: 'BIGINT', withPrecision: false, withScale: false }),
        new ColumnType({ id: 57, name: 'bigserial', description: '自動増分8バイト整数', baseQuery: 'BIGSERIAL', withPrecision: false, withScale: false, foreignId: 17 }),
        new ColumnType({ id: 31, name: 'real', description: '単精度浮動小数点 (4バイト)', baseQuery: 'REAL', withPrecision: false, withScale: false }),
        new ColumnType({ id: 33, name: 'double precision', description: '倍精度浮動小数点 (8バイト)', baseQuery: 'DOUBLE PRECISION', withPrecision: false, withScale: false }),
        new ColumnType({ id: 35, name: 'numeric', description: '精度の選択可能な高精度数値', baseQuery: 'NUMERIC', withPrecision: false, withScale: false }),
        new ColumnType({ id: 45, name: 'numeric (p, s)', description: '精度の選択可能な高精度数値', baseQuery: 'NUMERIC[[PARAM]]', withPrecision: true, withScale: true }),
        new ColumnType({ id: 101, name: 'date', description: '暦の日付 (年月日)', baseQuery: 'DATE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 131, name: 'time without time zone', description: '時刻 (時間帯なし)', baseQuery: 'TIME WITHOUT TIME ZONE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 132, name: 'time with time zone', description: '時間帯付き時刻', baseQuery: 'TIME WITH TIME ZONE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 141, name: 'time (p) without time zone', description: '時刻 (時間帯なし)', baseQuery: 'TIME[[PARAM]] WITHOUT TIME ZONE', withPrecision: true, withScale: false }),
        new ColumnType({ id: 142, name: 'time (p) with time zone', description: '時間帯付き時刻', baseQuery: 'TIME[[PARAM]] WITH TIME ZONE', withPrecision: true, withScale: false }),
        new ColumnType({ id: 111, name: 'timestamp without time zone', description: '日付と時刻 (時間帯なし)', baseQuery: 'TIMESTAMP WITHOUT TIME ZONE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 112, name: 'timestamp with time zone', description: '時間帯付き日付と時刻', baseQuery: 'TIMESTAMP WITH TIME ZONE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 121, name: 'timestamp (p) without time zone', description: '日付と時刻 (時間帯なし)', baseQuery: 'TIMESTAMP[[PARAM]] WITHOUT TIME ZONE', withPrecision: true, withScale: false }),
        new ColumnType({ id: 122, name: 'timestamp (p) with time zone', description: '時間帯付き日付と時刻', baseQuery: 'TIMESTAMP[[PARAM]] WITH TIME ZONE', withPrecision: true, withScale: false }),
        new ColumnType({ id: 301, name: 'char', description: '固定長文字列', baseQuery: 'CHAR', withPrecision: false, withScale: false }),
        new ColumnType({ id: 302, name: 'varchar', description: '可変長文字列', baseQuery: 'VARCHAR', withPrecision: false, withScale: false }),
        new ColumnType({ id: 311, name: 'char (n)', description: '固定長文字列', baseQuery: 'CHAR[[PARAM]]', withPrecision: true, withScale: false }),
        new ColumnType({ id: 312, name: 'varchar (n)', description: '可変長文字列', baseQuery: 'VARCHAR[[PARAM]]', withPrecision: true, withScale: false }),
        new ColumnType({ id: 325, name: 'text', description: '可変長文字列', baseQuery: 'TEXT', withPrecision: false, withScale: false }),
        new ColumnType({ id: 411, name: 'uuid', description: '汎用一意識別子', baseQuery: 'UUID', withPrecision: false, withScale: false }),
        new ColumnType({ id: 421, name: 'json', description: 'テキストのJSONデータ', baseQuery: 'JSON', withPrecision: false, withScale: false }),
        new ColumnType({ id: 422, name: 'jsonb', description: 'バイナリ JSON データ, 展開型', baseQuery: 'JSONB', withPrecision: false, withScale: false }),
        new ColumnType({ id: 431, name: 'xml', description: 'XMLデータ', baseQuery: 'XML', withPrecision: false, withScale: false }),
        new ColumnType({ id: 441, name: 'money', description: '貨幣金額', baseQuery: 'MONEY', withPrecision: false, withScale: false }),
        new ColumnType({ id: 451, name: 'tsquery', description: 'テキスト検索問い合わせ', baseQuery: 'TSQUERY', withPrecision: false, withScale: false }),
        new ColumnType({ id: 453, name: 'tsvector', description: 'テキスト検索文書', baseQuery: 'TSVECTOR', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1011, name: 'point', description: '平面上の幾何学的点', baseQuery: 'POINT', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1021, name: 'line', description: '平面上の無限直線', baseQuery: 'LINE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1022, name: 'lseg', description: '平面上の線分', baseQuery: 'LSEG', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1031, name: 'box', description: '平面上の矩形', baseQuery: 'BOX', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1032, name: 'circle', description: '平面上の円', baseQuery: 'CIRCLE', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1041, name: 'path', description: '平面上の幾何学的経路', baseQuery: 'PATH', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1042, name: 'polygon', description: '平面上の閉じた幾何学的経路', baseQuery: 'POLYGON', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1111, name: 'cidr', description: 'IPv4もしくはIPv6ネットワークアドレス', baseQuery: 'CIDR', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1112, name: 'inet', description: 'IPv4もしくはIPv6ホストアドレス', baseQuery: 'INET', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1121, name: 'macaddr', description: 'MAC (Media Access Control)アドレス', baseQuery: 'MACADDR', withPrecision: false, withScale: false }),
        new ColumnType({ id: 1122, name: 'macaddr8', description: 'MAC (Media Access Control) アドレス (EUI-64 形式)', baseQuery: 'MACADDR8', withPrecision: false, withScale: false }),
        new ColumnType({ id: 9101, name: 'pg_lsn', description: 'PostgreSQLログシーケンス番号', baseQuery: 'PG_LSN', withPrecision: false, withScale: false }),
        new ColumnType({ id: 9102, name: 'pg_snapshot', description: 'ユーザレベルのトランザクションIDスナップショット', baseQuery: 'PG_SNAPSHOT', withPrecision: false, withScale: false }),
        ColumnType.EMPTY
    ]],

    ["mysql", [
        new ColumnType({ id: 1, name: 'bit', description: 'ビット値型', baseQuery: 'BIT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2, name: 'bit (m)', description: 'ビット値型', baseQuery: 'BIT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 6, name: 'boolean', description: 'TINYINT(1) のシノニム', baseQuery: 'BOOLEAN', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 10, name: 'tinyint', description: '非常に小さい整数。 符号付きの範囲は -128 から 127 です。 符号なしの範囲は 0 から 255 です。', baseQuery: 'TINYINT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 11, name: 'smallint', description: '小さい整数。 符号付きの範囲は -32768 から 32767 です。 符号なしの範囲は 0 から 65535 です。', baseQuery: 'SMALLINT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 13, name: 'mediumint', description: '中間サイズの整数。 符号付きの範囲は -8388608 から 8388607 です。 符号なしの範囲は 0 から 16777215 です。', baseQuery: 'MEDIUMINT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 15, name: 'int', description: '普通サイズの整数。 符号付きの範囲は -2147483648 から 2147483647 です。 符号なしの範囲は 0 から 4294967295 です。', baseQuery: 'INT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 17, name: 'bigint', description: '大きい整数。 符号付きの範囲は -9223372036854775808 から 9223372036854775807 です。 符号なしの範囲は 0 から 18446744073709551615 です。', baseQuery: 'BIGINT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 20, name: 'tinyint (m)', description: '非常に小さい整数。 符号付きの範囲は -128 から 127 です。 符号なしの範囲は 0 から 255 です。', baseQuery: 'TINYINT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: true, withAuthIncrement: false }),
        new ColumnType({ id: 21, name: 'smallint (m)', description: '小さい整数。 符号付きの範囲は -32768 から 32767 です。 符号なしの範囲は 0 から 65535 です。', baseQuery: 'SMALLINT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 23, name: 'mediumint (m)', description: '中間サイズの整数。 符号付きの範囲は -8388608 から 8388607 です。 符号なしの範囲は 0 から 16777215 です。', baseQuery: 'MEDIUMINT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 25, name: 'int (m)', description: '普通サイズの整数。 符号付きの範囲は -2147483648 から 2147483647 です。 符号なしの範囲は 0 から 4294967295 です。', baseQuery: 'INT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 27, name: 'bigint (m)', description: '大きい整数。 符号付きの範囲は -9223372036854775808 から 9223372036854775807 です。 符号なしの範囲は 0 から 18446744073709551615 です。', baseQuery: 'BIGINT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 31, name: 'float', description: '小さい (単精度) 浮動小数点数。 許可される値は、-3.402823466E+38 から -1.175494351E-38、0、および 1.175494351E-38 から 3.402823466E+38 です。', baseQuery: 'FLOAT', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 33, name: 'double', description: '普通サイズ (倍精度) の浮動小数点数。 許可されている値は、-1.7976931348623157E+308 から -2.2250738585072014E-308、0、および 2.2250738585072014E-308 から 1.7976931348623157E+308 です。', baseQuery: 'DOUBLE', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 35, name: 'decimal', description: '固定小数点数。 桁数10 (精度) で、小数点以下の桁数0です。', baseQuery: 'DECIMAL', withPrecision: false, withScale: false, withUnsigned: true, withAuthIncrement: true }),
        new ColumnType({ id: 41, name: 'float (m, d)', description: '小さい (単精度) 浮動小数点数。 許可される値は、-3.402823466E+38 から -1.175494351E-38、0、および 1.175494351E-38 から 3.402823466E+38 です。', baseQuery: 'FLOAT[[PARAM]]', withPrecision: true, withScale: true, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 42, name: 'float (p)', description: '浮動小数点数です。p は精度をビットで表現します。', baseQuery: 'FLOAT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 43, name: 'double (m, d)', description: '普通サイズ (倍精度) の浮動小数点数。 許可されている値は、-1.7976931348623157E+308 から -2.2250738585072014E-308、0、および 2.2250738585072014E-308 から 1.7976931348623157E+308 です。', baseQuery: 'DOUBLE[[PARAM]]', withPrecision: true, withScale: true, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 45, name: 'decimal (m, d)', description: '固定小数点数。 M は桁数の合計 (精度) で、D は小数点以下の桁数 (スケール) です。', baseQuery: 'DECIMAL[[PARAM]]', withPrecision: true, withScale: true, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 101, name: 'date', description: '日付です。 サポートしている範囲は "1000-01-01" から "9999-12-31" です。', baseQuery: 'DATE', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 131, name: 'time', description: '時間です。 範囲は、"-838:59:59.000000" から "838:59:59.000000" です。', baseQuery: 'TIME', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 141, name: 'time (p)', description: '時間です。 範囲は、"-838:59:59.000000" から "838:59:59.000000" です。', baseQuery: 'TIME[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 112, name: 'datetime', description: '日付と時間の組み合わせです。 サポートしている範囲は "1000-01-01 00:00:00.000000" から "9999-12-31 23:59:59.999999" です。', baseQuery: 'DATETIME', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 115, name: 'timestamp', description: 'タイムスタンプです。 範囲は "1970-01-01 00:00:01.000000" UTC から "2038-01-19 03:14:07.999999" UTC です。', baseQuery: 'TIMESTAMP', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 122, name: 'datetime (p)', description: '日付と時間の組み合わせです。 サポートしている範囲は "1000-01-01 00:00:00.000000" から "9999-12-31 23:59:59.999999" です。', baseQuery: 'DATETIME[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 125, name: 'timestamp (p)', description: 'タイムスタンプです。 範囲は "1970-01-01 00:00:01.000000" UTC から "2038-01-19 03:14:07.999999" UTC です。', baseQuery: 'TIMESTAMP[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 151, name: 'year', description: '4 桁形式の年。', baseQuery: 'YEAR', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 301, name: 'char', description: '格納時に必ず、指定された長さになるように右側がスペースで埋められる固定長文字列です。', baseQuery: 'CHAR', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 311, name: 'char (m)', description: '格納時に必ず、指定された長さになるように右側がスペースで埋められる固定長文字列です。', baseQuery: 'CHAR[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 312, name: 'varchar (m)', description: '可変長文字列です。', baseQuery: 'VARCHAR[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 321, name: 'tinytext', description: '最大長が 255 文字の TEXT カラム。', baseQuery: 'TINYTEXT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 323, name: 'text', description: '最大長が 65,535 文字の TEXT カラム。', baseQuery: 'TEXT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 324, name: 'text (m)', description: '最大長が 65,535 文字の TEXT カラム。', baseQuery: 'TEXT[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 325, name: 'longtext', description: '最大長が 4G 文字の TEXT カラム。', baseQuery: 'LONGTEXT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 3, name: 'binary (m)', description: 'バイナリバイト文字列を格納します。', baseQuery: 'BINARY[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 5, name: 'varbinary (m)', description: 'バイナリバイト文字列を格納します。', baseQuery: 'VARBINARY[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 361, name: 'tinyblob', description: '最大長が 255 バイトの BLOB カラム。', baseQuery: 'TINYBLOB', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 363, name: 'blob', description: '最大長が 65,535 バイトの BLOB カラム。', baseQuery: 'BLOB', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 364, name: 'blob (m)', description: '最大長が 65,535 バイトの BLOB カラム。', baseQuery: 'BLOB[[PARAM]]', withPrecision: true, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 365, name: 'mediumblob', description: '最大長が 16,777,215 バイトの BLOB カラム。', baseQuery: 'MEDIUMBLOB', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 367, name: 'longblob', description: '最大長が 4G バイトの BLOB カラム。', baseQuery: 'LONGBLOB', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 422, name: 'json', description: '文書の型式であるJSONデータを格納するために使用されるデータ型。', baseQuery: 'JSON', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2001, name: 'geometry', description: '空間データを格納するために使用されるデータ型。点、線、多角形、およびその他の形状を含めることができます。', baseQuery: 'GEOMETRY', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2011, name: 'point', description: 'GEOMETRYデータ型の1つであり、2次元空間上の単一の点を表します。', baseQuery: 'POINT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2012, name: 'linestring', description: 'GEOMETRYデータ型の1つであり、2次元空間上の複数の点を結ぶ直線セグメントの連続したセットを表します。', baseQuery: 'LINESTRING', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2013, name: 'polygon', description: 'GEOMETRYデータ型の1つであり、2次元平面上の単一の領域を表す閉じたループの集合です。', baseQuery: 'POLYGON', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2021, name: 'multipoint', description: 'GEOMETRYデータ型の1つであり、複数の点を表す複数のPOINTオブジェクトの集合です。', baseQuery: 'MULTIPOINT', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2022, name: 'multilinestring', description: 'GEOMETRYデータ型の1つであり、複数の線分を表す複数のLINESTRINGオブジェクトの集合です。', baseQuery: 'MULTILINESTRING', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2023, name: 'multipolygon', description: 'GEOMETRYデータ型の1つであり、複数のポリゴンを表す複数のPOLYGONオブジェクトの集合です。', baseQuery: 'MULTIPOLYGON', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2031, name: 'geometrycollection', description: 'GEOMETRYデータ型の1つであり、複数のGEOMETRYオブジェクトの集合を表します。', baseQuery: 'GEOMETRYCOLLECTION', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2101, name: 'enum', description: '文字列のリストの中から1つを選択するために使用されるデータ型。', baseQuery: 'ENUM', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        new ColumnType({ id: 2102, name: 'set', description: 'ENUMの拡張版であり、文字列のリストから複数の選択肢を選択するために使用されるデータ型。', baseQuery: 'SET', withPrecision: false, withScale: false, withUnsigned: false, withAuthIncrement: false }),
        ColumnType.EMPTY
    ]]
]);

export const findDatabaseColumns = (databaseType: DatabaseType) => databaseColumns.get(databaseType) ?? [];