import TableIndexSupport from "~/models/database/TableIndexSupport";

export type DatabaseType = "postgres" | "mysql"

export class Database {

    constructor(
        public readonly databaseType: DatabaseType,
        public readonly name: string,
        public readonly tableIndexSupport: TableIndexSupport,
        private readonly reservedWords: Set<string>,
        private readonly escapeChar: string
    ) { }

    public escape(org: string): string {
        if (this.reservedWords.has(org.toUpperCase()) === false) {
            return org;
        }

        return `${this.escapeChar}${org}${this.escapeChar}`;
    }
}

// cSpell:disable

const commonReservedWords = [
    "ALL", "AND", "ANY", "AS", "ASC", "BETWEEN", "BY", "CASE", "CHECK", "COLUMN", "CONSTRAINT", "CREATE",
    "CROSS", "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "DATABASE", "DEFAULT",
    "DELETE", "DESC", "DISTINCT", "DROP", "ELSE", "END", "EXISTS", "FALSE", "FETCH", "FOR", "FOREIGN",
    "FROM", "FULL", "GRANT", "GROUP", "HAVING", "IF", "IN", "INNER", "INSERT", "INTERSECT", "INTO", "IS",
    "JOIN", "KEY", "LEFT", "LIKE", "LIMIT", "NATURAL", "NOT", "NULL", "ON", "OR", "ORDER", "OUTER",
    "PRIMARY", "REFERENCES", "RETURN", "RIGHT", "SCHEMA", "SELECT", "SET", "TABLE", "THEN", "TO", "TRUE",
    "UNION", "UNIQUE", "UPDATE", "USER", "USING", "VALUES", "WHEN", "WHERE", "WITH"
];

const postgresReservedWords = [
    "ABORT", "ABSOLUTE", "ACCESS", "ACTION", "ADMIN", "AFTER", "AGGREGATE", "ALSO", "ALTER", "ALWAYS",
    "ANALYSE", "ANALYZE", "ARRAY", "ASSERTION", "ASSIGNMENT", "ASYMMETRIC", "AT", "ATOMIC", "ATTACH",
    "ATTRIBUTE", "AUTHORIZATION", "BACKWARD", "BEFORE", "BEGIN", "BIGINT", "BINARY", "BIT", "BOOLEAN",
    "BOTH", "BREADTH", "CACHE", "CALL", "CALLED", "CASCADE", "CASCADED", "CAST", "CATALOG", "CHAIN",
    "CHAR", "CHARACTER", "CHARACTERISTICS", "CHECKPOINT", "CLASS", "CLOSE", "CLUSTER", "COALESCE",
    "COLLATE", "COLLATION", "COLUMNS", "COMMENT", "COMMENTS", "COMMIT", "COMMITTED", "CONCURRENTLY",
    "CONFIGURATION", "CONFLICT", "CONNECTION", "CONSTRAINTS", "CONTENT", "CONTINUE", "CONVERSION", "COPY",
    "COST", "CSV", "CUBE", "CURRENT", "CURRENT_CATALOG", "CURRENT_ROLE", "CURRENT_SCHEMA", "CURSOR",
    "CYCLE", "DATA", "DAY", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFERRABLE", "DEFERRED",
    "DEFINER", "DELIMITER", "DELIMITERS", "DEPENDS", "DEPTH", "DEREFERENCE", "DETACH", "DICTIONARY",
    "DISABLE", "DISCARD", "DISTRIBUTED", "DO", "DOCUMENT", "DOMAIN", "DOUBLE", "EACH", "ENABLE",
    "ENCODING", "ENCRYPTED", "ENUM", "ESCAPE", "EVENT", "EXCEPT", "EXCLUDE", "EXCLUDING", "EXCLUSIVE",
    "EXECUTE", "EXPLAIN", "EXPRESSION", "EXTENSION", "EXTERNAL", "EXTRACT", "FAMILY", "FILTER",
    "FINALIZE", "FIRST", "FLOAT", "FOLLOWING", "FORCE", "FORWARD", "FREEZE", "FUNCTION", "FUNCTIONS",
    "GENERATED", "GLOBAL", "GRANTED", "GREATEST", "GROUPING", "GROUPS", "HANDLER", "HEADER", "HOLD",
    "HOUR", "IDENTITY", "ILIKE", "IMMEDIATE", "IMMUTABLE", "IMPLICIT", "IMPORT", "INCLUDE", "INCLUDING",
    "INCREMENT", "INDENT", "INDEX", "INDEXES", "INHERIT", "INHERITS", "INITIALLY", "INLINE", "INOUT",
    "INPUT", "INSENSITIVE", "INSTEAD", "INT", "INTEGER", "INTERVAL", "INVOKER", "ISNULL", "ISOLATION",
    "LABEL", "LANGUAGE", "LARGE", "LAST", "LATERAL", "LEADING", "LEAKPROOF", "LEAST", "LEVEL", "LISTEN",
    "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCATION", "LOCK", "LOCKED", "LOGGED", "MAPPING",
    "MATCH", "MATERIALIZED", "MAXVALUE", "METHOD", "MINUTE", "MINVALUE", "MODE", "MONTH", "MOVE", "NAME",
    "NAMES", "NATIONAL", "NCHAR", "NEW", "NEXT", "NFC", "NFD", "NFKC", "NFKD", "NO", "NONE", "NORMALIZE",
    "NORMALIZED", "NOTHING", "NOTIFY", "NOTNULL", "NOWAIT", "NULLIF", "NULLS", "NUMERIC", "OBJECT", "OF",
    "OFF", "OFFSET", "OIDS", "OLD", "ONLY", "OPERATOR", "OPTION", "OPTIONS", "ORDINALITY", "OTHERS",
    "OUT", "OVER", "OVERLAPS", "OVERLAY", "OVERRIDING", "OWNED", "OWNER", "PARALLEL", "PARSER", "PARTIAL",
    "PARTITION", "PASSING", "PASSWORD", "PLANS", "POLICY", "POSITION", "PRECEDING", "PRECISION",
    "PREPARE", "PREPARED", "PRESERVE", "PRIOR", "PRIVILEGES", "PROCEDURAL", "PROCEDURE", "PROCEDURES",
    "PROGRAM", "PUBLICATION", "QUOTE", "RANGE", "READ", "REAL", "REASSIGN", "RECHECK", "RECURSIVE",
    "REF", "REFERENCING", "REFRESH", "REINDEX", "RELATIVE", "RELEASE", "RENAME", "REPEATABLE", "REPLACE",
    "REPLICA", "RESET", "RESTART", "RESTRICT", "RETURNING", "RETURNS", "REVOKE", "ROLE", "ROLLBACK",
    "ROLLUP", "ROUTINE", "ROUTINES", "ROW", "ROWS", "RULE", "SAVEPOINT", "SCHEMAS", "SCROLL", "SEARCH",
    "SECOND", "SECURITY", "SEQUENCE", "SEQUENCES", "SERIALIZABLE", "SERVER", "SESSION", "SESSION_USER",
    "SETOF", "SETS", "SHARE", "SHOW", "SIMILAR", "SIMPLE", "SKIP", "SMALLINT", "SNAPSHOT", "SOME", "SQL",
    "STABLE", "STANDALONE", "START", "STATEMENT", "STATISTICS", "STDIN", "STDOUT", "STORAGE", "STORED",
    "STRICT", "STRIP", "SUBSTRING", "SYMMETRIC", "SYSID", "SYSTEM", "TABLES", "TABLESAMPLE",
    "TABLESPACE", "TEMP", "TEMPLATE", "TEMPORARY", "TEXT", "TIES", "TIME", "TIMESTAMP", "TRAILING",
    "TRANSACTION", "TRANSFORM", "TREAT", "TRIGGER", "TRIM", "TYPE", "TYPES", "UESCAPE", "UNBOUNDED",
    "UNCOMMITTED", "UNENCRYPTED", "UNKNOWN", "UNLISTEN", "UNLOGGED", "UNTIL", "VACUUM", "VALID",
    "VALIDATE", "VALIDATOR", "VALUE", "VARCHAR", "VARIADIC", "VARYING", "VERBOSE", "VERSION", "VIEW",
    "VIEWS", "VOLATILE", "WHITESPACE", "WINDOW", "WITHIN", "WITHOUT", "WORK", "WRAPPER", "WRITE", "XML",
    "XMLATTRIBUTES", "XMLCONCAT", "XMLELEMENT", "XMLEXISTS", "XMLFOREST", "XMLNAMESPACES", "XMLPARSE",
    "XMLPI", "XMLROOT", "XMLSERIALIZE", "XMLTABLE", "YEAR", "YES", "ZONE"
];

const mysqlReservedWords = [
    "ACCESSIBLE", "ACCOUNT", "ACTIVE", "ADD", "ADMIN", "AFTER", "AGAINST", "AGGREGATE", "ALGORITHM",
    "ALTER", "ALWAYS", "ANALYZE", "ASENSITIVE", "AT", "AUTOCOMMIT", "AUTOEXTEND_SIZE", "AUTO_INCREMENT",
    "AVG", "AVG_ROW_LENGTH", "BACKUP", "BEFORE", "BEGIN", "BIGINT", "BINARY", "BINLOG", "BIT", "BLOB",
    "BLOCK", "BOOL", "BOOLEAN", "BOTH", "BTREE", "BUFFER", "BYTE", "CACHE", "CALL", "CASCADE", "CASCADED",
    "CAST", "CATALOG_NAME", "CHAIN", "CHANGE", "CHANGED", "CHANNEL", "CHAR", "CHARACTER", "CHARSET",
    "CHECKSUM", "CIPHER", "CLASS_ORIGIN", "CLIENT", "CLONE", "CLOSE", "COALESCE", "CODE", "COLLATE",
    "COLLATION", "COLUMN_FORMAT", "COLUMN_NAME", "COLUMNS", "COMMENT", "COMMIT", "COMMITTED",
    "COMPLETION", "COMPONENT", "COMPRESSED", "COMPRESSION", "CONCURRENT", "CONDITION", "CONNECTION",
    "CONSISTENT", "CONSTRAINT_CATALOG", "CONSTRAINT_NAME", "CONSTRAINT_SCHEMA", "CONTAINS", "CONTEXT",
    "CONTINUE", "CONVERT", "CPU", "CREATE", "CUBE", "CUME_DIST", "CURRENT", "CURSOR", "CURSOR_NAME",
    "DATA", "DATABASES", "DATAFILE", "DATE", "DATETIME", "DAY", "DAY_HOUR", "DAY_MICROSECOND",
    "DAY_MINUTE", "DAY_SECOND", "DEALLOCATE", "DEC", "DECIMAL", "DECLARE", "DEFAULT", "DEFAULT_AUTH",
    "DEFINER", "DEFINITION", "DELAYED", "DELAY_KEY_WRITE", "DENSE_RANK", "DESCRIBE", "DESCRIPTION",
    "DES_KEY_FILE", "DETAIL", "DETERMINISTIC", "DIAGNOSTICS", "DIRECTORY", "DISABLE", "DISCARD", "DISK",
    "DISTINCT", "DISTINCTROW", "DIV", "DO", "DOUBLE", "DROP", "DUAL", "DUMPFILE", "DUPLICATE", "DYNAMIC",
    "EACH", "ELSEIF", "EMPTY", "ENABLE", "ENCLOSED", "ENCRYPTION", "ENDS", "ENGINE", "ENGINES", "ENUM",
    "ERROR", "ERRORS", "ESCAPE", "ESCAPED", "EVENT", "EVERY", "EXCEPT", "EXCHANGE", "EXCLUDE", "EXECUTE",
    "EXPANSION", "EXPIRE", "EXPLAIN", "EXPORT", "EXTENDED", "EXTENT_SIZE", "FAST", "FAULTS", "FETCH",
    "FIELDS", "FILE", "FILE_BLOCK_SIZE", "FILTER", "FIRST", "FIRST_VALUE", "FIXED", "FLOAT", "FLOAT4",
    "FLOAT8", "FLUSH", "FOLLOWING", "FOLLOWS", "FORCE", "FORMAT", "FOUND", "GENERAL", "GENERATED",
    "GEOMETRY", "GEOMETRYCOLLECTION", "GET", "GLOBAL", "GRANTS", "GROUPING", "GROUPS", "HANDLER", "HASH",
    "HELP", "HIGH_PRIORITY", "HISTOGRAM", "HISTORY", "HOST", "HOSTS", "HOUR", "HOUR_MICROSECOND",
    "HOUR_MINUTE", "HOUR_SECOND", "IDENTIFIED", "IGNORE", "IGNORE_SERVER_IDS", "IMPORT",
    "IMPORT_TABLESPACE", "INACTIVE", "INDEXES", "INFILE", "INITIAL_SIZE", "INOUT", "INSENSITIVE",
    "INSERT_METHOD", "INSTALL", "INSTANCE", "INT", "INT1", "INT2", "INT3", "INT4", "INT8", "INTEGER",
    "INTERVAL", "INTO", "INVISIBLE", "INVOKER", "IO", "IO_AFTER_GTIDS", "IO_BEFORE_GTIDS", "IO_THREAD",
    "IPC", "ISOLATION", "ISSUER", "ITERATE", "JSON", "JSON_TABLE", "KEYS", "KEY_BLOCK_SIZE", "KILL",
    "LAG", "LANGUAGE", "LAST", "LAST_VALUE", "LATERAL", "LEAD", "LEADING", "LEAVE", "LEAVES", "LESS",
    "LEVEL", "LINEAR", "LINES", "LINESTRING", "LIST", "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP",
    "LOCK", "LOCKED", "LOGS", "LONG", "LONGBLOB", "LONGTEXT", "LOOP", "LOW_PRIORITY", "MASTER",
    "MASTER_AUTO_POSITION", "MASTER_BIND", "MASTER_CONNECT_RETRY", "MASTER_DELAY",
    "MASTER_HEARTBEAT_PERIOD", "MASTER_HOST", "MASTER_LOG_FILE", "MASTER_LOG_POS", "MASTER_PASSWORD",
    "MASTER_PORT", "MASTER_RETRY_COUNT", "MASTER_SERVER_ID", "MASTER_SSL", "MASTER_SSL_CA",
    "MASTER_SSL_CAPATH", "MASTER_SSL_CERT", "MASTER_SSL_CIPHER", "MASTER_SSL_CRL", "MASTER_SSL_CRLPATH",
    "MASTER_SSL_KEY", "MASTER_SSL_VERIFY_SERVER_CERT", "MASTER_TLS_VERSION", "MASTER_USER", "MATCH",
    "MAXVALUE", "MEDIUMBLOB", "MEDIUMINT", "MEDIUMTEXT", "MEMBER", "MEMORY", "MERGE", "MESSAGE_TEXT",
    "MICROSECOND", "MIDDLEINT", "MIGRATE", "MINUTE", "MINUTE_MICROSECOND", "MINUTE_SECOND", "MODE",
    "MODIFIES", "MODIFY", "MONTH", "MULTILINESTRING", "MULTIPOINT", "MULTIPOLYGON", "MUTEX",
    "MYSQL_ERRNO", "NAME", "NAMES", "NATIONAL", "NCHAR", "NDB", "NDBCLUSTER", "NESTED",
    "NETWORK_NAMESPACE", "NEVER", "NEW", "NEXT", "NO", "NODEGROUP", "NONE", "NOWAIT", "NO_WAIT",
    "NO_WRITE_TO_BINLOG", "NULLS", "NUMBER", "NUMERIC", "NVARCHAR", "OF", "OFF", "OFFSET", "OJ", "OLD",
    "ONE", "ONLY", "OPEN", "OPTIMIZE", "OPTIMIZER_COSTS", "OPTION", "OPTIONAL", "OPTIONALLY", "OPTIONS",
    "ORDINALITY", "ORGANIZATION", "OTHERS", "OUT", "OUTFILE", "OVER", "OWNER", "PACK_KEYS", "PAGE",
    "PARSER", "PARSE_GCOL_EXPR", "PARTIAL", "PARTITION", "PARTITIONING", "PARTITIONS", "PASSWORD", "PATH",
    "PERSIST", "PERSIST_ONLY", "PHASE", "PLUGIN", "PLUGINS", "PLUGIN_DIR", "POINT", "POLYGON", "PORT",
    "PRECEDES", "PRECEDING", "PRECISION", "PREPARE", "PRESERVE", "PREV", "PRIVILEGES", "PROCEDURE",
    "PROCESS", "PROCESSLIST", "PROFILE", "PROFILES", "PROXY", "PURGE", "QUARTER", "QUERY", "QUICK",
    "RANGE", "RANK", "READ", "READS", "READ_ONLY", "READ_WRITE", "REAL", "REBUILD", "RECOVER",
    "RECURSIVE", "REDOFILE", "REDO_BUFFER_SIZE", "REDUNDANT", "REFERENCE", "REGEXP", "RELAY", "RELAYLOG",
    "RELAY_LOG_FILE", "RELAY_LOG_POS", "RELAY_THREAD", "RELEASE", "RELOAD", "REMOTE", "REMOVE", "RENAME",
    "REORGANIZE", "REPAIR", "REPEAT", "REPEATABLE", "REPLACE", "REPLICATE_DO_DB", "REPLICATE_DO_TABLE",
    "REPLICATE_IGNORE_DB", "REPLICATE_IGNORE_TABLE", "REPLICATE_REWRITE_DB", "REPLICATE_WILD_DO_TABLE",
    "REPLICATE_WILD_IGNORE_TABLE", "REPLICATION", "REQUIRE", "RESET", "RESIGNAL", "RESOURCE", "RESPECT",
    "RESTART", "RESTORE", "RESTRICT", "RESUME", "RETURNED_SQLSTATE", "RETURNS", "REUSE", "REVERSE",
    "REVOKE", "ROLE", "ROLLBACK", "ROLLUP", "ROTATE", "ROUTINE", "ROW", "ROWS", "ROW_COUNT", "ROW_FORMAT",
    "ROW_NUMBER", "RTREE", "SAVEPOINT", "SCHEDULE", "SCHEMA", "SCHEMA_NAME", "SECOND", "SECONDARY",
    "SECONDARY_ENGINE", "SECONDARY_LOAD", "SECONDARY_UNLOAD", "SECOND_MICROSECOND", "SECURITY",
    "SENSITIVE", "SEPARATOR", "SERIAL", "SERIALIZABLE", "SERVER", "SESSION", "SHARE", "SHOW", "SHUTDOWN",
    "SIGNAL", "SIGNED", "SIMPLE", "SLAVE", "SLOW", "SMALLINT", "SNAPSHOT", "SOCKET", "SOME", "SONAME",
    "SOUNDS", "SOURCE", "SPATIAL", "SPECIFIC", "SQL", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING",
    "SQL_AFTER_GTIDS", "SQL_AFTER_MTS_GAPS", "SQL_BEFORE_GTIDS", "SQL_BIG_RESULT", "SQL_BUFFER_RESULT",
    "SQL_CACHE", "SQL_CALC_FOUND_ROWS", "SQL_NO_CACHE", "SQL_SMALL_RESULT", "SQL_THREAD", "SQL_TSI_DAY",
    "SQL_TSI_HOUR", "SQL_TSI_MINUTE", "SQL_TSI_MONTH", "SQL_TSI_QUARTER", "SQL_TSI_SECOND",
    "SQL_TSI_WEEK", "SQL_TSI_YEAR", "SSL", "STACKED", "START", "STARTING", "STARTS", "STATS_AUTO_RECALC",
    "STATS_PERSISTENT", "STATS_SAMPLE_PAGES", "STATUS", "STOP", "STORAGE", "STORED", "STRAIGHT_JOIN",
    "STRING", "SUBCLASS_ORIGIN", "SUBJECT", "SUBPARTITION", "SUBPARTITIONS", "SUPER", "SUSPEND", "SWAPS",
    "SWITCHES", "SYSTEM", "TABLES", "TABLESPACE", "TABLE_CHECKSUM", "TABLE_NAME", "TEMPORARY",
    "TEMPTABLE", "TERMINATED", "TEXT", "THAN", "THREAD_PRIORITY", "TIES", "TIME", "TIMESTAMP",
    "TIMESTAMPADD", "TIMESTAMPDIFF", "TINYBLOB", "TINYINT", "TINYTEXT", "TO", "TRAILING", "TRANSACTION",
    "TRIGGER", "TRIGGERS", "TRUE", "TRUNCATE", "TYPE", "TYPES", "UNCOMMITTED", "UNDEFINED", "UNDO",
    "UNDOFILE", "UNDO_BUFFER_SIZE", "UNICODE", "UNINSTALL", "UNKNOWN", "UNLOCK", "UNSIGNED", "UNTIL",
    "UPGRADE", "USAGE", "USE", "USE_FRM", "UTC_DATE", "UTC_TIME", "UTC_TIMESTAMP", "VALIDATION", "VALUE",
    "VARBINARY", "VARCHAR", "VARCHARACTER", "VARIABLES", "VARYING", "VCPU", "VIEW", "VIRTUAL", "VISIBLE",
    "WAIT", "WARNINGS", "WEEK", "WEIGHT_STRING", "WHILE", "WINDOW", "WITHOUT", "WORK", "WRAPPER", "WRITE",
    "X509", "XA", "XID", "XML", "XOR", "YEAR", "YEAR_MONTH", "ZEROFILL"
];

// cSpell:enable

export type Databases = { [key in DatabaseType]: Database };

// cSpell: ignore SPGIST FULLTEXT
export const databases: Databases = {
    "postgres": new Database("postgres", "PostgreSQL",
        new TableIndexSupport(["UNIQUE"], ["BTREE", "HASH", "GIST", "SPGIST", "GIN", "BRIN"], true),
        new Set([...commonReservedWords, ...postgresReservedWords]),
        '"' // PostgreSQL uses double quotes as escape character
    ),
    "mysql": new Database("mysql", "MySQL",
        new TableIndexSupport(["UNIQUE", "FULLTEXT", "SPATIAL"], ["BTREE", "HASH"]),
        new Set([...commonReservedWords, ...mysqlReservedWords]),
        '`' // MySQL uses backticks as escape character
    ),
};