name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/pull_request_template.md'
      - '.github/dependabot.yml'
      - '.vscode/**'
      - '*.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    env:
      VITE_GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      VITE_GOOGLE_SITE_VERTIFICATION: ${{ secrets.GOOGLE_SITE_VERTIFICATION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Generate App Version
        run: |
          APP_VERSION="0.$(TZ=Asia/Tokyo date '+%y%m%d').$(TZ=Asia/Tokyo date '+%H%M%S')"
          echo "VITE_APP_VERSION=${APP_VERSION}" > .env
          echo "APP_VERSION=${APP_VERSION}" >> ${GITHUB_ENV}
          echo "Deploy app_version: ${APP_VERSION}"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Push git tag
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
          TAG_VERSION="github-page/v${APP_VERSION}"
          git tag -a "${TAG_VERSION}" -m "Version ${TAG_VERSION} - Auto-generated by GitHub Actions"
          git push origin "${TAG_VERSION}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
